---
title: "p8105_hw1_qz2527"
author: "kindle zhang"
date: "2023-09-16"
output: html_document
---

## Problem 1

```{r setup, include = FALSE}
library(tidyverse)
library(moderndive)
```

1. load the data set

```{r load data}
data("early_january_weather")
```

2. describe the data

```{r describe data}
summary(early_january_weather)
# or use head(early_january_weather)
data_row = nrow(early_january_weather)
data_col = ncol(early_january_weather)
mean_temp = mean(early_january_weather$temp)
```

the variables in this data set are: `r ls(early_january_weather)`

the size of the data set is `r data_row` rows and `r data_col` columns

the mean temputure is `r mean_temp`

3. plot 

make a data table first and use `ggplot` to plot the image

```{r plot scatter}
my_plot = tibble(
  x = early_january_weather$time_hour,
  y = early_january_weather$temp,
  humid = early_january_weather$humid
)
ggplot(my_plot, aes(x = x, y = y, group = humid)) + geom_point(aes(color = humid, size = 5))

ggsave("hw1_plot_1.png")
```







